# Generated by Django 4.1.3 on 2023-11-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='id1',
        ),
    ]
