# Generated by Django 4.1.3 on 2023-11-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_refund_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund_req',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
